<?php

declare(strict_types=1);

return [
    'argomenti' => ['title' => 'Argomenti', 'category' => 'Generali', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/argomenti.html'],
    'argomento' => ['title' => 'Argomento', 'category' => 'Generali', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/argomento.html'],
    'homepage' => ['title' => 'Homepage', 'category' => 'Generali', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/homepage.html'],
    'domande-frequenti' => ['title' => 'Domande frequenti', 'category' => 'Generali', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/domande-frequenti.html'],
    'risultati-ricerca' => ['title' => 'Risultati di ricerca', 'category' => 'Generali', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/risultati-ricerca.html'],
    'lista-risorse' => ['title' => 'Lista risorse', 'category' => 'Generali', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/lista-risorse.html'],
    'lista-categorie' => ['title' => 'Lista categorie', 'category' => 'Generali', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/lista-categorie.html'],
    'lista-risorse-categorie' => ['title' => 'Lista risorse e categorie', 'category' => 'Generali', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/lista-risorse-categorie.html'],
    'mappa-sito' => ['title' => 'Mappa del sito', 'category' => 'Generali', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/mappa-sito.html'],
    'amministrazione' => ['title' => 'Amministrazione', 'category' => 'Amministrazione', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/amministrazione.html'],
    'documenti-dati' => ['title' => 'Documenti e dati', 'category' => 'Amministrazione', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/documenti-dati.html'],
    'novita' => ['title' => 'Novita', 'category' => 'Novita', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/novita.html'],
    'novita-dettaglio' => ['title' => 'Notizia, comunicato, avviso', 'category' => 'Novita', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/novita-dettaglio.html'],
    'servizi' => ['title' => 'Servizi', 'category' => 'Servizi', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/servizi.html'],
    'servizi-categoria' => ['title' => 'Categoria di servizio', 'category' => 'Servizi', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/servizi-categoria.html'],
    'servizio-dettaglio' => ['title' => 'Scheda servizio', 'category' => 'Servizi', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/servizio-dettaglio.html'],
    'eventi' => ['title' => 'Eventi', 'category' => 'Vivere il Comune', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/eventi.html'],
    'evento-dettaglio' => ['title' => 'Evento', 'category' => 'Vivere il Comune', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/evento-dettaglio.html'],
    'appuntamento-01-ufficio' => ['title' => 'Appuntamento 01 ufficio', 'category' => 'Prenotazione Appuntamento', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/appuntamento-01-ufficio.html'],
    'appuntamento-01-ufficio-luogo' => ['title' => 'Appuntamento 01 ufficio luogo', 'category' => 'Prenotazione Appuntamento', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/appuntamento-01-ufficio-luogo.html'],
    'appuntamento-02-data-orario' => ['title' => 'Appuntamento 02 data orario', 'category' => 'Prenotazione Appuntamento', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/appuntamento-02-data-orario.html'],
    'appuntamento-03-dettagli' => ['title' => 'Appuntamento 03 dettagli', 'category' => 'Prenotazione Appuntamento', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/appuntamento-03-dettagli.html'],
    'appuntamento-04-richiedente' => ['title' => 'Appuntamento 04 richiedente', 'category' => 'Prenotazione Appuntamento', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/appuntamento-04-richiedente.html'],
    'appuntamento-04-richiedente-autenticato' => ['title' => 'Appuntamento 04 richiedente autenticato', 'category' => 'Prenotazione Appuntamento', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/appuntamento-04-richiedente-autenticato.html'],
    'appuntamento-05-riepilogo' => ['title' => 'Appuntamento 05 riepilogo', 'category' => 'Prenotazione Appuntamento', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/appuntamento-05-riepilogo.html'],
    'appuntamento-06-conferma' => ['title' => 'Appuntamento 06 conferma', 'category' => 'Prenotazione Appuntamento', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/appuntamento-06-conferma.html'],
    'assistenza-01-dati' => ['title' => 'Assistenza 01 dati', 'category' => 'Richiesta Assistenza', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/assistenza-01-dati.html'],
    'assistenza-02-conferma' => ['title' => 'Assistenza 02 conferma', 'category' => 'Richiesta Assistenza', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/assistenza-02-conferma.html'],
    'segnalazione-dettaglio' => ['title' => 'Segnalazione dettaglio', 'category' => 'Segnalazione Disservizio', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-dettaglio.html'],
    'segnalazione-01-privacy' => ['title' => 'Segnalazione 01 privacy', 'category' => 'Segnalazione Disservizio', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-01-privacy.html'],
    'segnalazione-02-dati' => ['title' => 'Segnalazione 02 dati', 'category' => 'Segnalazione Disservizio', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-02-dati.html'],
    'segnalazione-03-riepilogo' => ['title' => 'Segnalazione 03 riepilogo', 'category' => 'Segnalazione Disservizio', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-03-riepilogo.html'],
    'segnalazione-04-conferma' => ['title' => 'Segnalazione 04 conferma', 'category' => 'Segnalazione Disservizio', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-04-conferma.html'],
    'segnalazione-area-personale' => ['title' => 'Segnalazione area personale', 'category' => 'Segnalazione Disservizio', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazione-area-personale.html'],
    'segnalazioni-elenco' => ['title' => 'Segnalazioni elenco', 'category' => 'Segnalazione Disservizio', 'source' => 'https://italia.github.io/design-comuni-pagine-statiche/sito/segnalazioni-elenco.html'],
];
