name: Attest Release Artifacts

on:
  release:
    types: [published]

permissions:
  id-token: write
  attestations: write
<<<<<<< HEAD
  contents: write

jobs:
  attest_and_upload:
=======
  contents: read

jobs:
  attest:
>>>>>>> 0314e8a24 (.)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
<<<<<<< HEAD

      - name: Create Artifact
        run: |
          zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*"

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ github.event.repository.name }}.zip

      - name: Upload Artifact to Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ${{ github.event.repository.name }}.zip
=======
      - name: Create release artifact
        run: |
          zip -r ${{ github.event.repository.name }}.zip . -x ".git/*" ".github/*"
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: ${{ github.event.repository.name }}.zip
>>>>>>> 0314e8a24 (.)
